<?php

use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('menus')->insert(array(
            array(
                'name' => 'Header',
                'slug' => 'header',
                'locale' => 'en',
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'name' => 'القائمة العلوية',
                'slug' => 'header',
                'locale' => 'ar',
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),

            array(
                'name' => 'Footer1',
                'slug' => 'support',
                'locale' => 'en',
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'name' => 'القائمة السفلية الاولى',
                'slug' => 'support',
                'locale' => 'ar',
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),

            array(
                'name' => 'Footer2',
                'slug' => 'links',
                'locale' => 'en',
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'name' => 'القائمة السفلية الثانية',
                'slug' => 'links',
                'locale' => 'ar',
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            )
        ));


        \DB::table('menu_items')->insert(array(
            array(
                'menu_id' => 1,
                'name' => 'Finding',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => '/',
                'target' => '_self',
                'order' => '1',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 1,
                'name' => 'About Us',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => '/about',
                'target' => '_self',
                'order' => '2',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 1,
                'name' => 'Istanbul Real Estate',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'properties/istanbul',
                'target' => '_self',
                'order' => '3',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 1,
                'name' => 'Our Services',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'services',
                'target' => '_self',
                'order' => '4',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 1,
                'name' => 'Blogs & News',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'blog',
                'target' => '_self',
                'order' => '5',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 1,
                'name' => 'Contact Us',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'contact-us',
                'target' => '_self',
                'order' => '6',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),

            array(
                'menu_id' => 2,
                'name' => 'الرئيسية',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => '/',
                'target' => '_self',
                'order' => '1',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 2,
                'name' => 'من نحن',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => '/about',
                'target' => '_self',
                'order' => '2',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 2,
                'name' => 'عقارات اسطنبول',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'properties/istanbul',
                'target' => '_self',
                'order' => '3',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 2,
                'name' => 'خدماتنا',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'services',
                'target' => '_self',
                'order' => '4',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 2,
                'name' => 'المدونة والأخبار',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'blog',
                'target' => '_self',
                'order' => '5',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 2,
                'name' => 'اتصل بنا',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'contact-us',
                'target' => '_self',
                'order' => '6',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),

            array(
                'menu_id' => 3,
                'name' => 'About Us',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'about',
                'target' => '_self',
                'order' => '1',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 3,
                'name' => 'Our Services',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'services',
                'target' => '_self',
                'order' => '2',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 3,
                'name' => 'Contact Us',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'contact-us',
                'target' => '_self',
                'order' => '3',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 3,
                'name' => 'Be Our Agent',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'agents',
                'target' => '_self',
                'order' => '4',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 3,
                'name' => 'Request Property',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'request-property',
                'target' => '_self',
                'order' => '5',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),

            array(
                'menu_id' => 4,
                'name' => 'اتصل بنا',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'about',
                'target' => '_self',
                'order' => '1',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 4,
                'name' => 'خدماتنا',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'services',
                'target' => '_self',
                'order' => '2',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 4,
                'name' => 'اتصل بنا',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'contact-us',
                'target' => '_self',
                'order' => '3',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 4,
                'name' => 'كن وكيلا لدينا',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'agents',
                'target' => '_self',
                'order' => '4',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 4,
                'name' => 'اطلب عقارك',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'request-property',
                'target' => '_self',
                'order' => '5',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),

            array(
                'menu_id' => 5,
                'name' => 'Istanbul',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'properties/istanbul',
                'target' => '_self',
                'order' => '1',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 5,
                'name' => 'Blog',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'blog',
                'target' => '_self',
                'order' => '2',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 5,
                'name' => 'Join Us',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'joinus',
                'target' => '_self',
                'order' => '3',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 5,
                'name' => 'Add Your Property',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'add-property',
                'target' => '_self',
                'order' => '4',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),

            array(
                'menu_id' => 6,
                'name' => 'عقارات اسطنبول',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'properties/istanbul',
                'target' => '_self',
                'order' => '1',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 6,
                'name' => 'المدونة',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'blog',
                'target' => '_self',
                'order' => '2',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 6,
                'name' => 'انضم لنا',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'joinus',
                'target' => '_self',
                'order' => '3',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
            array(
                'menu_id' => 6,
                'name' => 'اضف عقارك',
                'class' => 'OptimistDigital\MenuBuilder\Classes\MenuItemStaticURL',
                'value' => 'add-property',
                'target' => '_self',
                'order' => '4',
                'enabled' => true,
                'created_at' => '2019-04-15 09:06:19',
                'updated_at' => '2019-05-01 12:04:39',
            ),
        ));
    }
}
